### ISSUE TITLE
URLs found but could not be indexed due to Code 403 (Permission Error)

### ISSUE THREAD

**Issue by kiwirafe** [goenning/google-indexing-script#13]
Hello:
Can someone help me with the following situation:

I have enabled the two APIs and added the ownership to the service account. The script can successfully crawl my sitemaps and find the correct URLs, but when processing, it encounters the following errors. This is the error I got:
```
📄 Processing url: http://(one of my URLs here)
🔐 This service account doesn't have access to this site.
Response was: 403
{
  "error": {
    "code": 403,
    "message": "Permission denied. Failed to verify the URL ownership.",
    "status": "PERMISSION_DENIED"
  }
}
```

![image](https://github.com/goenning/google-indexing-script/assets/30309285/b5016851-cdf1-44df-a127-1027d0cbca0a)

**Comment by kiwirafe** [comment]
Problem solved. It turns out that it should be `https` instead of `http` in the sitemap.

**Comment by doggy8088** [comment]
I got the same error, but I fixed the problem by changing the permissions in Google Search Console from `FULL` to `OWNER`. I don't know it's the right settings or not?

**Comment by kiwirafe** [comment]
Yes, that is the correct setting. I believe there are multiple ways that lead to the same Permission Error.
