### ISSUE TITLE
Help sir const accessToken = await getAccessToken();

### ISSUE THREAD

**Issue by JANCOKRAIMUBAWOK** [goenning/google-indexing-script#15]
> google-indexing-script@0.0.0 index
> node ./src/index.mjs "x.com"

file:///mnt/c/Users/Administrator/Documents/GITHUB/GITHUB/WP/google-indexing-script-main/google-indexing-script-main/src/index.mjs:22
const accessToken = await getAccessToken();
                    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by goenning** [comment]
you need a newer Nodejs version
