### ISSUE TITLE
how can i Download the JSON file with the credentials of the service account 。

### ISSUE THREAD

**Issue by cced3000** [goenning/google-indexing-script#2]
how can i Download the JSON file with the credentials of the service account.  I can't find a place to download it. Could you please provide more detailed instructions?

**Comment by 4troDev** [comment]
> how can i Download the JSON file with the credentials of the service account.  I can't find a place to download it. Could you please provide more detailed instructions?

To download the JSON file from Google Cloud:

1. Go to IAM & Admin, click on  "Service Accounts."
2. Select your service account, click on the "Keys" tab.
3. Add a new key, choose "Create new key."
4. Set "Key type" to "JSON" and click "Create."
5. Download the JSON file prompted by your browser.

Remember: It's a one-time download, consider temporary access for better security.

**Comment by goenning** [comment]
Thanks @4troDev

**Comment by AsianLazyMan** [comment]
Thank you so much @4troDev

**Comment by c4nzin** [comment]
you are a hero, thanks! @goenning
