### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by robingenz** [goenning/google-indexing-script#22]
First of all: Thank you very much for this great project! 

I would love to just install it globally via `npm install` and then use it as a CLI. Do you plan to release this script as an npm package?

**Comment by goenning** [comment]
I don't have plans to do it, but I'm happy to accept a PR that does it :)

**Comment by robingenz** [comment]
Awesome! 🙌 I will work on this in the next few weeks so that I can use your CLI in my new [GitHub action](https://github.com/robingenz/google-indexing-action).
