### ISSUE TITLE
Found 0 URLs in 1 sitemap

### ISSUE THREAD

**Issue by ghost** [goenning/google-indexing-script#26]
Hi, thank you for putting this together.

When I run the command on a domain-verified property, I get this:

🔎 Processing site: sc-domain:example.com
👉 Found 0 URLs in 1 sitemap

👍 Done, here's the status of all 0 pages:

✨ There are no pages that can be indexed. Everything is already indexed!

Despite the sitemap having multiple URLs that haven't been indexed yet. I tried with another domain-verified property and I got the same error.

After a few hours, I tried again with two other URL prefix properties, and it worked.

 Processing site: https://www.example.com/
👉 Found 209 URLs in 1 sitemap
📦 Batch 1 of 5 complete
📦 Batch 2 of 5 complete
📦 Batch 3 of 5 complete
📦 Batch 4 of 5 complete
📦 Batch 5 of 5 complete

👍 Done, here's the status of all 209 pages:
• ✅ Submitted and indexed: 56 pages
• ❓ URL is unknown to Google: 8 pages
• 👀 Crawled - currently not indexed: 129 pages
• 👀 Discovered - currently not indexed: 9 pages
• ❌ Excluded by ‘noindex’ tag: 2 pages
• ❌ Alternate page with proper canonical tag: 1 pages
• ❌ Not found (404): 4 pages

✨ Found 146 pages that can be indexed.
etc.

**Comment by warbell** [comment]
After a few hours, I tried again with another property, and it worked.

👉 Found 209 URLs in 1 sitemap
📦 Batch 1 of 5 complete
📦 Batch 2 of 5 complete
📦 Batch 3 of 5 complete
📦 Batch 4 of 5 complete
📦 Batch 5 of 5 complete

👍 Done, here's the status of all 209 pages:
• ✅ Submitted and indexed: 56 pages
• ❓ URL is unknown to Google: 8 pages
• 👀 Crawled - currently not indexed: 129 pages
• 👀 Discovered - currently not indexed: 9 pages
• ❌ Excluded by ‘noindex’ tag: 2 pages
• ❌ Alternate page with proper canonical tag: 1 pages
• ❌ Not found (404): 4 pages

✨ Found 146 pages that can be indexed.

**Comment by goenning** [comment]
That's explained on the readme, there's a different between a URL and Domain property in GSC
