### ISSUE TITLE
This service account doesn't have access to this site.

### ISSUE THREAD

**Issue by julesvcode** [goenning/google-indexing-script#3]
I'm getting the below output although I did add the service account with Owner permission on my site using the `client_email` property and moved the `service_account.json` file to the folder with the script. Any idea why?

🔐 This service account doesn't have access to this site.
❌ No sitemaps found, add them to Google Search Console and try again.

**Comment by worldzhao** [comment]
> I'm getting the below output although I did add the service account with Owner permission on my site using the `client_email` property and moved the `service_account.json` file to the folder with the script. Any idea why?
> 
> 🔐 This service account doesn't have access to this site. ❌ No sitemaps found, add them to Google Search Console and try again.

Adding `https://` in front of the domain name worked for me, I don't know why it's inconsistent with the description in the README.md.

<img width="847" alt="image" src="https://github.com/goenning/google-indexing-script/assets/25662450/c7dab9e6-e353-4223-823e-09d7ef2f1d53">

<img width="682" alt="image" src="https://github.com/goenning/google-indexing-script/assets/25662450/9236bd99-d234-43d9-84f2-2d29f859385a">

**Comment by milosmns** [comment]
+1, I also got the error but should have used `https://` in front to get it to work.

**Comment by goenning** [comment]
Thanks for the feedback. I'll update the docs. If you add your site as a `Domain Property` on GSC, they you have to run as `npm run index seogets.com`, otherwise if it's a URL Prefix property, then it has to be the name of your site with `https://`

**Comment by AmirSa12** [comment]
I am getting the same error while I have added my sites both as a Domain Property and URL prefix on GSC, they both have the owner permission as well (the client_mail) . any idea what could be causing the issue?

**Comment by Trimester6** [comment]
> I am getting the same error while I have added my sites both as a Domain Property and URL prefix on GSC, they both have the owner permission as well (the client_mail) . any idea what could be causing the issue?

You probably didn't set email from google service account with full access, works for me.

**Comment by btahir** [comment]
I'm having this issue as well. My Google Cloud Account is separate from my Google Search Console. I added the formers email as a site owner but that didn't seem to work. Will this only work if everything's under one Google account?
