### ISSUE TITLE
0 urls found

### ISSUE THREAD

**Issue by federicocappellotto97** [goenning/google-indexing-script#30]
I'm running it like this
`npm run index andreaponzio.com`
It found a sitemap, since i'm logging it, but it doesn't find any url even if there are 3 pages, and two are already indexed
This is the result
```
npm run index andreaponzio.com

> google-indexing-script@0.0.0 index
> ts-node ./src/index.ts andreaponzio.com

🔎 Processing site: sc-domain:andreaponzio.com
Sitemaps: [ 'https://www.andreaponzio.com/sitemap.xml' ] 1
👉 Found 0 URLs in 1 sitemap
👍 Done, here's the status of all 0 pages:

✨ There are no pages that can be indexed. Everything is already indexed!

👍 All done!
💖 Brought to you by https://seogets.com - SEO Analytics.
```

**Comment by goenning** [comment]
I suspect there’s something in your sitemap that the script is unable to parse, hence why it’s showing 0 pages.

it looks ok to me when I eyeball it, so it might be a bug on our parser or something minor invalid on the sitemap. Would you be interested in troubleshooting it?

**Comment by federicocappellotto97** [comment]
> I suspect there’s something in your sitemap that the script is unable to parse, hence why it’s showing 0 pages.
> 
> it looks ok to me when I eyeball it, so it might be a bug on our parser or something minor invalid on the sitemap. Would you be interested in troubleshooting it?

Yes, i can debug more in the next days 👍

**Comment by antoinekm** [comment]
Hey @federicocappellotto97, I've done a few tests and I'm really not getting the same result as you. Perhaps a screen record would be helpful to understand better.
<img width="722" alt="image" src="https://github.com/goenning/google-indexing-script/assets/54948363/e3a9f4ca-03eb-48ee-91bd-452d62c776cd">

**Comment by federicocappellotto97** [comment]
> Hey @federicocappellotto97, I've done a few tests and I'm really not getting the same result as you. Perhaps a screen record would be helpful to understand better. <img alt="image" width="722" src="https://private-user-images.githubusercontent.com/54948363/309227435-e3a9f4ca-03eb-48ee-91bd-452d62c776cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODg5ODksIm5iZiI6MTcwOTI4ODY4OSwicGF0aCI6Ii81NDk0ODM2My8zMDkyMjc0MzUtZTNhOWY0Y2EtMDNlYi00OGVlLTkxYmQtNDUyZDYyYzc3NmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMWMzMTNiM2I5OGMwYWZiMDA4ZjU4ZTljMjViZmI2MzZmYTI0ZTIxZDdkYjgyMjliMTliOTMzYjM4OTJiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AqpilPzD8wYwG0dENg8NzpHpjIQbiAk0OKZR9GOH3EU">

I think i found the problem, my company firewall was blocking the requests. Now i tried with another network and it works! Thank you for your support! :)
