### ISSUE TITLE
Script blocked

### ISSUE THREAD

**Issue by absoluteweb** [goenning/google-indexing-script#32]
Hi,
I don't know if this is due to my configuration, but recently the script has been blocked, regardless of the domain entered.

> google-indexing-script@0.0.0 index
> ts-node ./src/index.ts domain.tld

Everything up to date (node, google indexing script).

**Comment by goenning** [comment]
no logs or anything?

**Comment by absoluteweb** [comment]
False alarm, it's back on as strangely as it happened, it's working again.
