### ISSUE TITLE
[ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory

### ISSUE THREAD

**Issue by kaltsturm** [goenning/google-indexing-script#34]
I executed "npm run build" and receive

CLI Building entry: src/bin.ts, src/cli.ts, src/index.ts, src/shared/auth.ts, src/shared/gsc.ts, src/shared/index.ts, src/shared/sitemap.ts, src/shared/types.ts, src/shared/utils.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.0.2
CLI Using tsup config: xxxxxxxxxxxxx/google-indexing-script/tsup.config.ts
CLI Target: esnext
CLI Cleaning output folder
CJS Build start
ESM You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
CJS dist/shared/utils.js       355.00 B
CJS dist/bin.js                401.00 B
CJS dist/cli.js                460.00 B
CJS dist/chunk-LWWEROSD.js     388.00 B
CJS dist/index.js              1.08 KB
CJS dist/chunk-LBCQ44KW.js     4.51 KB
CJS dist/shared/auth.js        271.00 B
CJS dist/shared/gsc.js         579.00 B
CJS dist/shared/index.js       1.02 KB
CJS dist/chunk-75CVEFN6.js     669.00 B
CJS dist/chunk-74KA7FXM.js     1.43 KB
CJS dist/chunk-2MKILNFN.js     3.54 KB
CJS dist/shared/sitemap.js     307.00 B
CJS dist/chunk-MEQJBOPJ.js     1.36 KB
CJS dist/chunk-TTTS3QMW.js     807.00 B
CJS dist/shared/types.js       264.00 B
CJS dist/chunk-XL3RXX4H.js     708.00 B
CJS dist/chunk-IL7T5FML.js     692.00 B
CJS dist/shared/utils.js.map   51.00 B
CJS dist/bin.js.map            136.00 B
CJS dist/cli.js.map            51.00 B
CJS dist/chunk-LWWEROSD.js.map 230.00 B
CJS dist/index.js.map          51.00 B
CJS dist/chunk-LBCQ44KW.js.map 8.75 KB
CJS dist/shared/auth.js.map    51.00 B
CJS dist/shared/gsc.js.map     51.00 B
CJS dist/shared/index.js.map   51.00 B
CJS dist/chunk-75CVEFN6.js.map 376.00 B
CJS dist/chunk-74KA7FXM.js.map 2.72 KB
CJS dist/chunk-2MKILNFN.js.map 7.01 KB
CJS dist/shared/sitemap.js.map 51.00 B
CJS dist/chunk-MEQJBOPJ.js.map 2.68 KB
CJS dist/chunk-TTTS3QMW.js.map 2.76 KB
CJS dist/shared/types.js.map   51.00 B
CJS dist/chunk-XL3RXX4H.js.map 841.00 B
CJS dist/chunk-IL7T5FML.js.map 51.00 B
CJS ⚡️ Build success in 225ms
DTS Build start
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
    at [kOnExit] (node:internal/worker:313:26)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
Emitted 'error' event on Worker instance at:
    at [kOnExit] (node:internal/worker:313:12)
    at Worker.<computed>.onexit (node:internal/worker:229:20) {
  code: 'ERR_WORKER_OUT_OF_MEMORY'
}

**Comment by antoinekm** [comment]
Hey @kaltsturm,

You actually need to increase the memory limit of js heap, one possible way to do it is to set `NODE_OPTIONS` env variable to `NODE_OPTIONS="--max_old_space_size=4096"`, it will sets the maximum heap size to 4 GB. Adjust the value according to your worker capabilities.
