### ISSUE TITLE
Can not find the package google-indexing-script

### ISSUE THREAD

**Issue by AsianLazyMan** [goenning/google-indexing-script#35]
Hi, all. 
As the title
![image](https://github.com/goenning/google-indexing-script/assets/42577440/10f53faa-8b45-4fba-afbb-1917ca910002)
![image](https://github.com/goenning/google-indexing-script/assets/42577440/e860d664-3335-4a60-8290-7ff84fdb7a70)

**Comment by goenning** [comment]
The package should now be on NPM, want to try again?
https://www.npmjs.com/package/google-indexing-script

@AntoineKM for some reason the GH actions failed, but the package was uploaded. I've already set the NPM_TOKEN variable

**Comment by AsianLazyMan** [comment]
> The package should now be on NPM, want to try again? https://www.npmjs.com/package/google-indexing-script
> 
> @AntoineKM for some reason the GH actions failed, but the package was uploaded. I've already set the NPM_TOKEN variable

Thank you very much for replying to me so quickly. Now I can pull this package normally. Thank you very much.

**Comment by antoinekm** [comment]
It should be fine now @AsianLazyMan 😁
