### ISSUE TITLE
Hey does this script support subdomains?

### ISSUE THREAD

**Issue by sysadev** [goenning/google-indexing-script#37]
It always fail whenever I try to index subdomain, I setup a URL prefix for the subdomain.

```
🔎 Processing site: sc-domain:sub.example.com
🔐 This service account doesn't have access to this site.
❌ No sitemaps found, add them to Google Search Console and try again.
```

**Comment by antoinekm** [comment]
Hey @shoaiyb,

Did you activate these apis:
- https://console.cloud.google.com/apis/api/searchconsole.googleapis.com
- https://console.cloud.google.com/apis/api/indexing.googleapis.com

**Comment by antoinekm** [comment]
Okay, I'll do some tests of my own and get back to you.

**Comment by sysadev** [comment]
> Hey @shoaiyb,
> 
> Did you activate these apis:
> 
> * https://console.cloud.google.com/apis/api/searchconsole.googleapis.com
> * https://console.cloud.google.com/apis/api/indexing.googleapis.com

Of course I did.

**Comment by sysadev** [comment]
> Okay, I'll do some tests of my own and get back to you.

I believe the issue is from the [`sc-domain`](https://github.com/goenning/google-indexing-script/blob/9478b8a7b53d310d93ddf14ce2e8d6a89bb445a6/src/shared/gsc.ts#L8) thing, isn't it for root domain?

**Comment by goenning** [comment]
no, that can be used for subdomains too. but if your property is a URL Prefix property then you have to remove it. @AntoineKM what you think of improving this? we could try both with/without the sc-domain prefix, then try with https:// as well until we find a property that has sitemaps? lot of people getting confused by that

**Comment by antoinekm** [comment]
I did my tests, it works, but you need to have a property on the subdomain on Google Search Console, because it's a different property.

<img width="317" alt="image" src="https://github.com/goenning/google-indexing-script/assets/54948363/ef2d5a76-21ac-474e-8995-0ed870a0ed18">

**Comment by antoinekm** [comment]
> ut if your property is a URL Prefix property then you have to remove it. @AntoineKM what you think of improving this? we could try both with/without the sc-domain prefix,

Yes, we can do that!

**Comment by sysadev** [comment]
It works now that I use the patch: `git clone --depth 1 --branch "antoinekm/recheck-opposite-property" https://github.com/ArkeeAgency/google-indexing-script.git`
