### ISSUE TITLE
Error 403 Permission denied. Failed to verify the URL ownership

### ISSUE THREAD

**Issue by junlim0505** [goenning/google-indexing-script#58]
🔐 This service account doesn't have access to this site.
Response was: 403
{
  "error": {
    "code": 403,
    "message": "Permission denied. Failed to verify the URL ownership.",
    "status": "PERMISSION_DENIED"
  }
}

When I run the program, error 403 appears at the end.
Did I set something wrong?

**Comment by erwannbst** [comment]
Same error for me

**Comment by fiddler** [comment]
I got this as well until I changed the role of the service account user in the Google Search Console to "Owner" under Settings > Users and Permissions. Hope this helps!

**Comment by egemenkalecik** [comment]
I tried every way but I couldn't find a solution. It gives me an error.

**Comment by diptnc** [comment]
> I got this as well until I changed the role of the service account user in the Google Search Console to "Owner" under Settings > Users and Permissions. Hope this helps!

Thanks it worked!
