### ISSUE TITLE
API's and limitation

### ISSUE THREAD

**Issue by tibrworks** [goenning/google-indexing-script#6]
Hi buddy!

Which api will limit the consumption of the tool? Thinking about automating it to run 1x a day on all my sites?

Ps: Your tool is absolutely fantastic, I ran the repository today, super easy to use! Congratulations!

**Comment by goenning** [comment]
The indexing api is 200 per day

**Comment by tibrworks** [comment]
Thanks!

Have an option to increase that limit on API on google cloud?

**Comment by tibrworks** [comment]
https://cloud.google.com/api-keys/docs/quotas here we have the explanation! Thanks mate, absolute fantastic tool...also i'm testing seogets too!
