### ISSUE TITLE
Prevent script from exiting the process

### ISSUE THREAD

**Issue by marcelscruz** [goenning/google-indexing-script#60]
I have a script that runs on a GitHub action, which calls 3 times the indexing script, each time for a different URL.

Because of rate limiting, they all use different Google keys.

The problem is that, if the first one fails, the whole GitHub action exits, even though they're individually wrapped in `try...catch` blocks.

Any chance this could be changed, and left for the dev to decide when to exit the process?

Thanks!

**Comment by goenning** [comment]
I think it's best to run that in 3 separate jobs on github action, instead of 3 steps in the same job
either that OR there might be an option on github action to ignore failed steps

**Comment by marcelscruz** [comment]
That's a good idea, thank you Guilherme!
