### ISSUE TITLE
Forced reindex command

### ISSUE THREAD

**Issue by phenomen** [goenning/google-indexing-script#7]
On some websites I manage there are pages that are changing rather frequently.
It would be great if there was some command that forces indexing of selected page i.e. `npm run reindex <url>` even if this page is already known and indexed. While I can do that directly from Search Console, it's very slow.

**Comment by khyamay** [comment]
@phenomen agreed, would be nice to have command to reindex.

**Comment by antoinekm** [comment]
I will soon add this feature 😉

**Comment by antoinekm** [comment]
I haven't forgotten, it's just that it's a bit more complicated than I thought, because we've totally changed our vision, since we've got the CLI, the command would be `gis --urls=https://domain.com/page1,https://domain.com/page2` ? I'm a bit out of ideas...

**Comment by phenomen** [comment]
> I haven't forgotten, it's just that it's a bit more complicated than I thought, because we've totally changed our vision, since we've got the CLI, the command would be `gis --urls=https://domain.com/page1,https://domain.com/page2` ? I'm a bit out of ideas...

It would be fine I guess. To make it a bit shorter, you can also use `--domain=https://domain.com --url=/page1,/page2,/page3/subpath1`

**Comment by antoinekm** [comment]
Done in #65
